name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.173.37.15
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd node-financial-api/node-financial-api
            git fetch --all
            git reset --hard origin/main
            npm install
            npx prisma generate
            pm2 reload financial-api

          # health check
            sleep 5
            curl -f http://localhost:3000/health